releases:
    - name: sachi-app
      chart: testsachi/test
      values:
      - replicaCount: 1
        image:
          repository: nginx
          pullPolicy: IfNotPresent
          tag: "1.18.0"
repositories:
- name: testsachi
  url: https://demondevilhades.github.io/helm-charts
