releases:
    - name: mongodb-app
      chart: mongodb/sample-app
      values:
      - replicaCount: 1
        image:
         frontend:
           repository: quay.io/mongodb/farm-intro-frontend
         backend:
           repository: quay.io/mongodb/farm-intro-backend
           pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
           tag: "0.1"
repositories:
- name: sample-app
  url: https://mongodb.github.io/helm-charts
